Importing **library**

In [1]:
import pandas as pd #loadind dataset
import numpy as np #to perform array

choosing dataset from local directory

In [3]:
from google.colab import files
upload=files.upload()

Saving ad sale prediction data set.csv to ad sale prediction data set.csv


Loading the dataset

In [4]:
dataset = pd.read_csv("ad sale prediction data set.csv")
print(dataset)

    AGE  SALARY  STATUS
0    44   45598       1
1    36   94355       1
2    43   47310       0
3    20  125497       0
4    25  114509       0
..  ...     ...     ...
70   41   54573       0
71   55   84189       0
72   22   67527       0
73   23   42333       1
74   47  103735       0

[75 rows x 3 columns]


Summarizing Data

In [6]:
print(dataset.shape)# size of dataset
print(dataset.head(2))# head-first n values
print(dataset.tail(2))#tail- last n values

(75, 3)
   AGE  SALARY  STATUS
0   44   45598       1
1   36   94355       1
    AGE  SALARY  STATUS
73   23   42333       1
74   47  103735       0


Splitting dataset into dependent and independent variable (ip and op)

In [7]:
x= dataset.iloc[:,:-1].values #input /independent variable
y=dataset.iloc[:,-1].values#output/ dependent variable

Splitting dataset into train and test dataset

In [8]:
from sklearn.model_selection import train_test_split 
#train_test_split returns 4 variables x_train,x_test,y_train,y_test
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=0)

Feature scaling
here we are using standard scaling method (StandardScaler())

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train = sc.fit_transform(x_train) #fit transform - calculate mean and variance of each of the feature in our data 
x_test= sc.transform(x_test)#transform- transform all the features using respective mean nd variance

[[-1.043567   -0.84321739]
 [-0.09747604 -1.42242737]
 [-0.09747604  0.27788166]
 [ 0.76260666  0.7444568 ]
 [ 1.79470589  0.82748458]
 [-1.21558354  0.34087267]
 [-0.01146777  1.32059404]
 [-1.30159181 -0.78131465]
 [-1.21558354 -1.43145352]
 [ 0.50458185  0.3720801 ]
 [-0.78554219  2.21226244]
 [ 1.79470589 -0.99518959]
 [-0.52751739  0.212138  ]
 [ 0.59059012 -0.5006718 ]
 [ 0.84861492 -0.33349597]]


Training - Algorithm Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegression
model= LogisticRegression(random_state = 0)
model.fit(x_train,y_train)

LogisticRegression(random_state=0)

Predicting 

In [14]:
age=int(input("Enter Customer's age: "))
salary=int(input("Enter Customer's salary: "))
newval=[[age,salary]]
result= model.predict(sc.transform(newval))
print(result)
if result == 1:
  print("customer will buy")
else:
  print("customer will not buy")

Enter Customer's age: 21
Enter Customer's salary: 90000
[0]
customer will not buy


prediction for all test sets

In [16]:
y_pred = model.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 0]]


Validation

In [17]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print("CONFUSION MATRIX")
print(cm)
print("ACCURACY OF THE MODEL:{0}".format(accuracy_score(y_test,y_pred)*100))

CONFUSION MATRIX
[[8 2]
 [5 0]]
ACCURACY OF THE MODEL:53.333333333333336
